In [1]:
import pandas as pd
data = {
    "id":[1,2,3,4,5,6,7,8,9,10],
    "name":["Alice","Bob","Carol","David","Eva","Frank","Grace","Helen","Ian","Jack"],
    "department":["IT","HR","IT","Sales","HR","Sales","IT","Marketing","Marketing","HR"],
    "salary":[70000,50000,90000,60000,55000,65000,80000,52000,58000,62000],
    "age":[29,34,41,30,28,33,38,26,31,45]
}

df = pd.DataFrame(data)

In [3]:
q1 = df
df

   id   name department  salary  age
0   1  Alice         IT   70000   29
1   2    Bob         HR   50000   34
2   3  Carol         IT   90000   41
3   4  David      Sales   60000   30
4   5    Eva         HR   55000   28
5   6  Frank      Sales   65000   33
6   7  Grace         IT   80000   38
7   8  Helen  Marketing   52000   26
8   9    Ian  Marketing   58000   31
9  10   Jack         HR   62000   45

In [4]:
#employee with salary greater than 60000
q2 = df[df["salary"] > 60000][["name","salary"]]
q2

    name  salary
0  Alice   70000
2  Carol   90000
5  Frank   65000
6  Grace   80000
9   Jack   62000

In [5]:
q3=df["salary"].mean()
q3

np.float64(64200.0)

In [14]:
q4=df.loc[df["department"]=="IT","name"]
q4

0    Alice
2    Carol
6    Grace
Name: name, dtype: str

In [19]:
q5=df.groupby("department").size().reset_index(name="employee_count")
q5

  department  employee_count
0         HR               3
1         IT               3
2  Marketing               2
3      Sales               2

In [38]:
q6 = df["salary"].max()
q6

np.int64(90000)

In [39]:
q7 = df.sort_values("salary", ascending=False)
q7

   id   name department  salary  age
2   3  Carol         IT   90000   41
6   7  Grace         IT   80000   38
0   1  Alice         IT   70000   29
5   6  Frank      Sales   65000   33
9  10   Jack         HR   62000   45
3   4  David      Sales   60000   30
8   9    Ian  Marketing   58000   31
4   5    Eva         HR   55000   28
7   8  Helen  Marketing   52000   26
1   2    Bob         HR   50000   34

In [42]:
q8=df.loc[df["age"]>30,["name","age"]]
q8

    name  age
1    Bob   34
2  Carol   41
5  Frank   33
6  Grace   38
8    Ian   31
9   Jack   45

In [43]:
q9 = df.groupby("department")["salary"].mean().reset_index()
q9

  department        salary
0         HR  55666.666667
1         IT  80000.000000
2  Marketing  55000.000000
3      Sales  62500.000000

In [44]:
q10 = df[df["salary"] == df["salary"].max()]
q10

   id   name department  salary  age
2   3  Carol         IT   90000   41

In [46]:
q11 = df.groupby("department")["salary"].sum().reset_index()
q11

  department  salary
0         HR  167000
1         IT  240000
2  Marketing  110000
3      Sales  125000

In [47]:
q12 = (df["age"] > 30).sum()
q12

np.int64(6)

In [52]:
q13 = df.groupby("department")["salary"].mean().reset_index()
q13 = q13.loc[q13["salary"] > 60000, ["department","salary"]]
q13

  department   salary
1         IT  80000.0
3      Sales  62500.0

In [54]:
q14 = df["department"].unique()
q14

<StringArray>
['IT', 'HR', 'Sales', 'Marketing']
Length: 4, dtype: str

In [55]:
q15 = df.nlargest(3,"salary")