# **PART A**

In [3]:
import pandas as pd

data = {
        "name": [
            "Smartphone X", "Laptop Pro", "Wireless Earbuds", "Gaming Console", "Bluetooth Speaker",
            "Men T-Shirt", "Women Jacket", "Running Shoes", "Jeans", "Sneakers",
            "Mystery Novel", "Python Programming", "Data Science Handbook", "Cookbook Deluxe", "Children Story Book",
            "Vacuum Cleaner", "Air Fryer", "LED Lamp", "Coffee Maker", "Blender",
            "4K Monitor", "Smartwatch"
        ],
        "category": [
            "Electronics","Electronics","Electronics","Electronics","Electronics",
            "Clothing","Clothing","Clothing","Clothing","Clothing",
            "Books","Books","Books","Books","Books",
            "Home","Home","Home","Home","Home",
            "Electronics","Electronics"
        ],
        "price": [
            15000, 55000, 2500, 35000, 1800,
            500, 2500, 3000, 2000, 3500,
            300, 800, 1200, 1500, 250,
            7000, 9000, 1200, 4500, 3000,
            22000, 8000
        ],
        "stock": [
            50, 30, 100, 20, 75,
            200, 80, 60, 120, 90,
            300, 150, 100, 70, 250,
            40, 35, 150, 60, 80,
            25, 45
        ],
        "rating": [
            4.5,4.7,4.2,4.6,4.1,
            3.9,4.3,4.0,3.8,4.2,
            4.5,4.8,4.6,4.1,4.0,
            4.3,4.4,3.9,4.2,4.1,
            4.7,4.4
        ],
        "num_reviews": [
            320,210,150,180,90,
            75,60,110,50,95,
            140,200,170,80,60,
            120,110,45,130,100,
            160,140
        ]
    }
df = pd.DataFrame(data)

In [6]:
print(df.head())
print(df.tail())

                name     category  price  stock  rating  num_reviews
0       Smartphone X  Electronics  15000     50     4.5          320
1         Laptop Pro  Electronics  55000     30     4.7          210
2   Wireless Earbuds  Electronics   2500    100     4.2          150
3     Gaming Console  Electronics  35000     20     4.6          180
4  Bluetooth Speaker  Electronics   1800     75     4.1           90
            name     category  price  stock  rating  num_reviews
17      LED Lamp         Home   1200    150     3.9           45
18  Coffee Maker         Home   4500     60     4.2          130
19       Blender         Home   3000     80     4.1          100
20    4K Monitor  Electronics  22000     25     4.7          160
21    Smartwatch  Electronics   8000     45     4.4          140

In [9]:
print(df.shape)
print(df.dtypes)
df.columns

(22, 6)
name               str
category           str
price            int64
stock            int64
rating         float64
num_reviews      int64
dtype: object

Index(['name', 'category', 'price', 'stock', 'rating', 'num_reviews'], dtype='str')

In [14]:
df["category"].describe()

count              22
unique              4
top       Electronics
freq                7
Name: category, dtype: object

In [12]:
df.isnull().sum()

name           0
category       0
price          0
stock          0
rating         0
num_reviews    0
dtype: int64

In [15]:
df["category"].value_counts()

category
Electronics    7
Clothing       5
Books          5
Home           5
Name: count, dtype: int64

# **LOC Function**

In [27]:
#selecting specific columns.syntax for returning all columns : df.loc[df["category"] == "Electronics"]
electronics = df.loc[df["category"] == "Electronics",["name","category","price"]]
electronics

                 name     category  price
0        Smartphone X  Electronics  15000
1          Laptop Pro  Electronics  55000
2    Wireless Earbuds  Electronics   2500
3      Gaming Console  Electronics  35000
4   Bluetooth Speaker  Electronics   1800
20         4K Monitor  Electronics  22000
21         Smartwatch  Electronics   8000

In [22]:
high_rating=df.loc[(df["rating"]>4.0) & (df["price"]<5000)]
high_rating

                     name     category  price  stock  rating  num_reviews
2        Wireless Earbuds  Electronics   2500    100     4.2          150
4       Bluetooth Speaker  Electronics   1800     75     4.1           90
6            Women Jacket     Clothing   2500     80     4.3           60
9                Sneakers     Clothing   3500     90     4.2           95
10          Mystery Novel        Books    300    300     4.5          140
11     Python Programming        Books    800    150     4.8          200
12  Data Science Handbook        Books   1200    100     4.6          170
13        Cookbook Deluxe        Books   1500     70     4.1           80
18           Coffee Maker         Home   4500     60     4.2          130
19                Blender         Home   3000     80     4.1          100

In [29]:
df.loc[0:3,["name","category"]]

               name     category
0      Smartphone X  Electronics
1        Laptop Pro  Electronics
2  Wireless Earbuds  Electronics
3    Gaming Console  Electronics

In [19]:
df.loc[df["name"] == "Smartphone X", "stock"] = 45
df.loc[df["name"] == "Smartphone X"]

           name     category  price  stock  rating  num_reviews
0  Smartphone X  Electronics  15000     45     4.5          320

# **iLOC**

In [30]:
df.iloc[:5]

                name     category  price  stock  rating  num_reviews
0       Smartphone X  Electronics  15000     45     4.5          320
1         Laptop Pro  Electronics  55000     30     4.7          210
2   Wireless Earbuds  Electronics   2500    100     4.2          150
3     Gaming Console  Electronics  35000     20     4.6          180
4  Bluetooth Speaker  Electronics   1800     75     4.1           90

In [31]:
df.iloc[-5:]

            name     category  price  stock  rating  num_reviews
17      LED Lamp         Home   1200    150     3.9           45
18  Coffee Maker         Home   4500     60     4.2          130
19       Blender         Home   3000     80     4.1          100
20    4K Monitor  Electronics  22000     25     4.7          160
21    Smartwatch  Electronics   8000     45     4.4          140

In [32]:
df.iloc[::2]

                     name     category  price  stock  rating  num_reviews
0            Smartphone X  Electronics  15000     45     4.5          320
2        Wireless Earbuds  Electronics   2500    100     4.2          150
4       Bluetooth Speaker  Electronics   1800     75     4.1           90
6            Women Jacket     Clothing   2500     80     4.3           60
8                   Jeans     Clothing   2000    120     3.8           50
10          Mystery Novel        Books    300    300     4.5          140
12  Data Science Handbook        Books   1200    100     4.6          170
14    Children Story Book        Books    250    250     4.0           60
16              Air Fryer         Home   9000     35     4.4          110
18           Coffee Maker         Home   4500     60     4.2          130
20             4K Monitor  Electronics  22000     25     4.7          160

In [35]:
df.iloc[10:16,0:4]

                     name category  price  stock
10          Mystery Novel    Books    300    300
11     Python Programming    Books    800    150
12  Data Science Handbook    Books   1200    100
13        Cookbook Deluxe    Books   1500     70
14    Children Story Book    Books    250    250
15         Vacuum Cleaner     Home   7000     40

# **Filtered DataFrames**

In [40]:
budget_products = df.loc[df["price"]<1000]
budget_products

                   name  category  price  stock  rating  num_reviews
5           Men T-Shirt  Clothing    500    200     3.9           75
10        Mystery Novel     Books    300    300     4.5          140
11   Python Programming     Books    800    150     4.8          200
14  Children Story Book     Books    250    250     4.0           60

In [41]:
premium_products = df.loc[df["price"]>10000]
premium_products

              name     category  price  stock  rating  num_reviews
0     Smartphone X  Electronics  15000     45     4.5          320
1       Laptop Pro  Electronics  55000     30     4.7          210
3   Gaming Console  Electronics  35000     20     4.6          180
20      4K Monitor  Electronics  22000     25     4.7          160

In [43]:
popular_products = df.loc[(df["num_reviews"]>100) & (df["rating"]>4.0)]
popular_products

                     name     category  price  stock  rating  num_reviews
0            Smartphone X  Electronics  15000     45     4.5          320
1              Laptop Pro  Electronics  55000     30     4.7          210
2        Wireless Earbuds  Electronics   2500    100     4.2          150
3          Gaming Console  Electronics  35000     20     4.6          180
10          Mystery Novel        Books    300    300     4.5          140
11     Python Programming        Books    800    150     4.8          200
12  Data Science Handbook        Books   1200    100     4.6          170
15         Vacuum Cleaner         Home   7000     40     4.3          120
16              Air Fryer         Home   9000     35     4.4          110
18           Coffee Maker         Home   4500     60     4.2          130
20             4K Monitor  Electronics  22000     25     4.7          160
21             Smartwatch  Electronics   8000     45     4.4          140

In [46]:
filtered_dfs = {
    "budget_products": budget_products,
    "premium_products": premium_products,
    "popular_products": popular_products
}

for name, dataframe in filtered_dfs.items():
    filename = f"{name}.csv"
    dataframe.to_csv(filename, index=False)
    print(f"Saved {filename}")

Saved budget_products.csv
Saved premium_products.csv
Saved popular_products.csv

# **PART B**

In [47]:
jan_data = {
    "product": ["Laptop", "Phone", "Tablet", "Headphones", "Monitor", "Phone", "Laptop"],
    "units_sold": [5, 12, 6, 10, 4, 8, 3],
    "price": [60000, 30000, 20000, 5000, 15000, 30000, 60000]
}

feb_data = {
    "product": ["Laptop", "Phone", "Tablet", "Headphones", "Monitor", "Phone", "Tablet"],
    "units_sold": [6, 10, 8, 9, 5, 7, 4],
    "price": [60000, 30000, 20000, 5000, 15000, 30000, 20000]
}

mar_data = {
    "product": ["Laptop", "Phone", "Tablet", "Headphones", "Monitor", "Phone", "Laptop"],
    "units_sold": [7, 9, 5, 12, 6, 10, 4],
    "price": [60000, 30000, 20000, 5000, 15000, 30000, 60000]
}

jan_df = pd.DataFrame(jan_data)
feb_df = pd.DataFrame(feb_data)
mar_df = pd.DataFrame(mar_data)

jan_df, feb_df, mar_df

(      product  units_sold  price
 0      Laptop           5  60000
 1       Phone          12  30000
 2      Tablet           6  20000
 3  Headphones          10   5000
 4     Monitor           4  15000
 5       Phone           8  30000
 6      Laptop           3  60000,
       product  units_sold  price
 0      Laptop           6  60000
 1       Phone          10  30000
 2      Tablet           8  20000
 3  Headphones           9   5000
 4     Monitor           5  15000
 5       Phone           7  30000
 6      Tablet           4  20000,
       product  units_sold  price
 0      Laptop           7  60000
 1       Phone           9  30000
 2      Tablet           5  20000
 3  Headphones          12   5000
 4     Monitor           6  15000
 5       Phone          10  30000
 6      Laptop           4  60000)

## **Summary Comparison**

In [63]:
summary_df = pd.DataFrame(
    index=["January", "February", "March"],
    columns=["Total Revenue", "Average Order Value", "Top Selling Product"]
)

month_map = {
    "January": jan_df,
    "February": feb_df,
    "March": mar_df
}

for month, df in month_map.items():

    df["revenue"] = df["price"] * df["units_sold"]

    total_revenue = df["revenue"].sum()
    total_orders = df["units_sold"].sum()
    avg_order_value = total_revenue / total_orders

    top_product = (
        df.groupby("product")["units_sold"]
        .sum()
        .idxmax()
    )

    summary_df.loc[month] = [total_revenue, avg_order_value, top_product]

summary_df

         Total Revenue Average Order Value Top Selling Product
January        1310000        27291.666667               Phone
February       1230000        25102.040816               Phone
March          1480000        27924.528302               Phone

In [64]:
jan_df.query("revenue > 100000")

  product  units_sold  price  revenue
0  Laptop           5  60000   300000
1   Phone          12  30000   360000
2  Tablet           6  20000   120000
5   Phone           8  30000   240000
6  Laptop           3  60000   180000

In [65]:
feb_df.query("units_sold > 8")

      product  units_sold  price  revenue
1       Phone          10  30000   300000
3  Headphones           9   5000    45000

In [66]:
sales = pd.concat(
    [jan_df.assign(month="January"),
     feb_df.assign(month="February"),
     mar_df.assign(month="March")]
)

sales

      product  units_sold  price  revenue     month
0      Laptop           5  60000   300000   January
1       Phone          12  30000   360000   January
2      Tablet           6  20000   120000   January
3  Headphones          10   5000    50000   January
4     Monitor           4  15000    60000   January
5       Phone           8  30000   240000   January
6      Laptop           3  60000   180000   January
0      Laptop           6  60000   360000  February
1       Phone          10  30000   300000  February
2      Tablet           8  20000   160000  February
3  Headphones           9   5000    45000  February
4     Monitor           5  15000    75000  February
5       Phone           7  30000   210000  February
6      Tablet           4  20000    80000  February
0      Laptop           7  60000   420000     March
1       Phone           9  30000   270000     March
2      Tablet           5  20000   100000     March
3  Headphones          12   5000    60000     March
4     Monitor           6  15000    90000     March
5       Phone          10  30000   300000     March
6      Laptop           4  60000   240000     March

## Q1: Difference Between `.loc[]` and `.iloc[]`

### `.loc[]`
- Label-based indexing
- Uses **row/column names**
- Slice **end is inclusive**

Example:

In [67]:
df = pd.DataFrame(
    {"A": [10, 20, 30, 40, 50]},
    index=[0, 1, 2, 3, 4]
)

df.loc[0:3]

    A
0  10
1  20
2  30
3  40

The result includes rows **0 through 3** because `.loc` includes the end index.

### `.iloc[]`
- Position-based indexing
- Uses **integer positions**
- Slice **end is exclusive**

In [69]:
df.iloc[0:3]

    A
0  10
1  20
2  30

The result includes rows **0,1,2** because `.iloc` excludes the end position.

---

### csv_analyser

In [71]:
def analyze_csv(filepath):

    df = pd.read_csv(filepath)

    print("===== FIRST 5 MINUTES CHECKLIST =====")

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    print(df.head())

    print("\nData types:")
    print(df.dtypes)

    print("\nMissing values:")
    print(df.isnull().sum())

    print("\nSummary statistics:")
    print(df.describe())

    num_rows, num_cols = df.shape

    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    categorical_cols = df.select_dtypes(exclude="number").columns.tolist()

    null_counts = df.isnull().sum().to_dict()

    memory_mb = df.memory_usage(deep=True).sum() / (1024**2)

    return {
        "num_rows": num_rows,
        "num_cols": num_cols,
        "numeric_cols": numeric_cols,
        "categorical_cols": categorical_cols,
        "null_counts": null_counts,
        "memory_mb": memory_mb
    }

In [72]:
report = analyze_csv("budget_products.csv")
print(report)

===== FIRST 5 MINUTES CHECKLIST =====

Shape:
(4, 6)

Columns:
['name', 'category', 'price', 'stock', 'rating', 'num_reviews']

First 5 rows:
                  name  category  price  stock  rating  num_reviews
0          Men T-Shirt  Clothing    500    200     3.9           75
1        Mystery Novel     Books    300    300     4.5          140
2   Python Programming     Books    800    150     4.8          200
3  Children Story Book     Books    250    250     4.0           60

Data types:
name               str
category           str
price            int64
stock            int64
rating         float64
num_reviews      int64
dtype: object

Missing values:
name           0
category       0
price          0
stock          0
rating         0
num_reviews    0
dtype: int64

Summary statistics:
            price       stock    rating  num_reviews
count    4.000000    4.000000  4.000000     4.000000
mean   462.500000  225.000000  4.300000   118.750000
std    249.582986   64.549722  0.424264    64.339594
min    250.000000  150.000000  3.900000    60.000000
25%    287.500000  187.500000  3.975000    71.250000
50%    400.000000  225.000000  4.250000   107.500000
75%    575.000000  262.500000  4.575000   155.000000
max    800.000000  300.000000  4.800000   200.000000
{'num_rows': 4, 'num_cols': 6, 'numeric_cols': ['price', 'stock', 'rating', 'num_reviews'], 'categorical_cols': ['name', 'category'], 'null_counts': {'name': 0, 'category': 0, 'price': 0, 'stock': 0, 'rating': 0, 'num_reviews': 0}, 'memory_mb': np.float64(0.000701904296875)}

In [73]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "salary": [50000, 60000, 70000]
})

# Fix 1: Use & instead of 'and' for element-wise conditions
high_earners = df[(df["age"] > 25) & (df["salary"] > 55000)]

# Fix 2: Avoid chained indexing, use .loc for assignment
df.loc[0, "age"] = 26

# Fix 3: iloc slice end is exclusive, so use 0:3 to include rows 0,1,2
first_three = df.iloc[0:3]

print("High earners:")
print(high_earners)

print("\nUpdated DataFrame:")
print(df)

print(f"\nGot {len(first_three)} rows, expected 3")

High earners:
      name  age  salary
1      Bob   30   60000
2  Charlie   35   70000

Updated DataFrame:
      name  age  salary
0    Alice   26   50000
1      Bob   30   60000
2  Charlie   35   70000

Got 3 rows, expected 3